apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: cloudsql-proxy
spec:
 replicas: 1
 template:
  metadata:
   labels:
    app: cloudsql-proxy
    unit: mycloudsql
  spec:
   volumes:
    - name: cloudsql-instance-credentials
      secret:
       secretName: cloudsql-instance-credentials
    - name: cloudsql
      emptyDir: 
   containers:
    - name: cloudsql-proxy
      image: gcr.io/cloudsql-docker/gce-proxy:1.11
      command: ["/cloud_sql_proxy", "-instances=wave25-vladoi:us-central1:mysql-marian=tcp:0.0.0.0:3306","-credential_file=secrets/cloudsql/credentials.json"]
      volumeMounts:
       - name: cloudsql-instance-credentials
         mountPath: /secrets/cloudsql
         readOnly: true    

       

